name: Generate SVG JSON

on:
  push:
    paths:
      - 'Patches/**'

  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notebook nbconvert

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute Generate\ SVG\ Json.ipynb

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Update index.html from Jupyter Notebook"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}